// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7VczwQTyGkjweFnaPWSJOO6HDWuOJnU',
    appId: '1:497946122788:web:6d3c59dc5fea73b9b9d6b1',
    messagingSenderId: '497946122788',
    projectId: 'school-of-performing-arts',
    authDomain: 'school-of-performing-arts.firebaseapp.com',
    storageBucket: 'school-of-performing-arts.appspot.com',
    measurementId: 'G-PP52K1GVHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAJxLFBgAExfB7wZH-nZH0kbFe9pJ7nA',
    appId: '1:497946122788:android:81dbcb468b1ec97eb9d6b1',
    messagingSenderId: '497946122788',
    projectId: 'school-of-performing-arts',
    storageBucket: 'school-of-performing-arts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6cj1kg4Hs8wiR3N4wf-nGrtaGjNydDDA',
    appId: '1:497946122788:ios:e0a36c4142bdbaf7b9d6b1',
    messagingSenderId: '497946122788',
    projectId: 'school-of-performing-arts',
    storageBucket: 'school-of-performing-arts.appspot.com',
    iosClientId:
        '497946122788-i86j4ugli14kh430guoqi4qe90ttkhqk.apps.googleusercontent.com',
    iosBundleId: 'nl.schoolofperformingarts.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6cj1kg4Hs8wiR3N4wf-nGrtaGjNydDDA',
    appId: '1:497946122788:ios:e0a36c4142bdbaf7b9d6b1',
    messagingSenderId: '497946122788',
    projectId: 'school-of-performing-arts',
    storageBucket: 'school-of-performing-arts.appspot.com',
    iosClientId:
        '497946122788-i86j4ugli14kh430guoqi4qe90ttkhqk.apps.googleusercontent.com',
    iosBundleId: 'nl.schoolofperformingarts.app',
  );
}
