name: Android Build & Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ios: 
    name: Build Flutter Android
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'android'
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Auth codesigning
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'     
          flutter-version: 3.27.4    
          
      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: android build_and_deploy
          subdirectory: android
        env:
          GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}