name: Build and sign iOS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build Flutter iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'ios'

      - name: Auth codesigning
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.4

      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: ios release
          subdirectory: ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORECONNECT_PRIVATE_KEY: "${{ secrets.APPLE_API_KEY }}"